# Generated by Django 5.0 on 2023-12-21 19:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullFIO', models.TextField(default='', max_length=100)),
                ('FIO', models.TextField(default='', max_length=100)),
                ('Date', models.DateField(auto_now=True)),
                ('Specialty', models.TextField(default='', max_length=100)),
                ('FullKafedra', models.TextField(default='', max_length=100)),
                ('Kafedra', models.TextField(default='', max_length=100)),
                ('Birthday', models.DateField(default=datetime.date.today)),
                ('Passport_Number', models.TextField(default='', max_length=100)),
                ('Passport_Vidacha', models.TextField(default='', max_length=100)),
                ('Passport_Date', models.DateField(default=datetime.date.today)),
                ('Registration_Address', models.TextField(default='', max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.form')),
            ],
        ),
    ]
