# Generated by Django 5.0 on 2023-12-21 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Date', models.DateField(auto_now=True)),
                ('FullFIO', models.TextField(default='', max_length=100)),
                ('FIO', models.TextField(default='', max_length=100)),
                ('Specialty', models.TextField(default='', max_length=100)),
                ('FullKafedra', models.TextField(default='', max_length=100)),
                ('Kafedra', models.TextField(default='', max_length=100)),
                ('Birthday', models.DateField(default=datetime.date.today)),
                ('Passport_Number', models.TextField(default='', max_length=100)),
                ('Passport_Vidacha', models.TextField(default='', max_length=100)),
                ('Passport_Date', models.DateField(default=datetime.date.today)),
                ('Registration_Address', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
