# Generated by Django 5.0 on 2023-12-22 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_form1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='form1',
            name='FIO',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form1',
            name='FullFIO',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form1',
            name='FullKafedra',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Kafedra',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Passport_Number',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Passport_Vidacha',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Registration_Address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form1',
            name='Specialty',
            field=models.TextField(max_length=100),
        ),
    ]
